// Copyright (c) 2026 StackAndPointer
// SPDX-License-Identifier: MIT
//
// Using a header generated by tools/header_to_ash.py. Generate the wrapper,
// then include it here exactly like a normal header:
//
//   python tools\header_to_ash.py include\GameApi.h \
//     --dll GameApi.dll --output SigilHook\GameApi.ash --arch x86
//
// The generated file defines typed wrappers such as SHNativeAdd(a, b).

#include "SigilHook.ash"
// #include "GameApi.ash"

uint64 g_nativeBindingHook = SH_INVALID_HANDLE;

void onNativeBinding() {
    // Example of calling a generated wrapper. Uncomment once GameApi.ash exists.
    // const int result = SHNativeAdd(6, 7);
    // shLog("GameApi result computed");
    shKeepOriginal();
}

void setupNativeBinding() {
    // const uint64 target = shNativeAddress("GameApi.dll", "GameApiEntry", "cdecl");
    // g_nativeBindingHook = shHookScript(target, "void onNativeBinding()", "int:int");
}

void unloadNativeBinding() {
    if (shIsValidHook(g_nativeBindingHook)) {
        shDestroyHook(g_nativeBindingHook);
        g_nativeBindingHook = SH_INVALID_HANDLE;
    }
}
